# Generated by Django 5.2.5 on 2026-04-25 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_reaction_one_per_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_muted', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('muted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('other_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_states_as_other', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_archived', 'updated_at'], name='chat_conver_user_id_9a2ecc_idx'), models.Index(fields=['user', 'is_muted'], name='chat_conver_user_id_463f10_idx'), models.Index(fields=['user', 'other_user'], name='chat_conver_user_id_262963_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'other_user'), name='unique_conversation_state_per_pair'), models.CheckConstraint(condition=models.Q(('user', models.F('other_user')), _negated=True), name='prevent_self_conversation_state')],
            },
        ),
    ]
