# Generated by Django 5.2.5 on 2026-05-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_block_notification_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('follow', 'Follow'), ('new_post', 'New Post'), ('friend_request', 'Friend Request'), ('friend_accepted', 'Friend Accepted'), ('post_like', 'Post Like'), ('post_comment', 'Post Comment')], max_length=20),
        ),
    ]
